import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { MemberSummaryData } from "@/app/actions/reports";
import type { CoopOverviewData } from "@/app/actions/reports";

const FOOTER_TEXT = "Confidential — Generated by Cooperative Manager";

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.getHeight();
    const pageWidth = doc.internal.pageSize.getWidth();
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(FOOTER_TEXT, pageWidth / 2, pageHeight - 10, { align: "center" });
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 15, pageHeight - 10, {
      align: "right",
    });
  }
}

export function exportMemberStatementPdf(
  data: MemberSummaryData,
  cooperativeName: string
) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const today = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  // ── Header ──────────────────────────────────────────────────
  doc.setFontSize(18);
  doc.setTextColor(20, 20, 20);
  doc.text(cooperativeName, pageWidth / 2, 20, { align: "center" });

  doc.setFontSize(13);
  doc.setTextColor(60, 60, 60);
  doc.text("Member Financial Statement", pageWidth / 2, 29, {
    align: "center",
  });

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`${data.memberName}  ·  ${data.memberEmail}`, pageWidth / 2, 37, {
    align: "center",
  });
  doc.text(`Report Date: ${today}`, pageWidth / 2, 43, { align: "center" });

  // Divider
  doc.setDrawColor(220, 220, 220);
  doc.line(15, 47, pageWidth - 15, 47);

  // ── Summary Table ────────────────────────────────────────────
  const fmt = (n: number) => n.toLocaleString();

  const available = Math.max(
    0,
    data.totalVerifiedContributions - data.activeLoanBalance
  );

  autoTable(doc, {
    startY: 53,
    head: [["Metric", "Amount"]],
    body: [
      ["Total Verified Contributions", `${fmt(data.totalVerifiedContributions)}`],
      ["Active Loan Balance", `${fmt(data.activeLoanBalance)}`],
      ["Available (Contributions − Loan Balance)", `${fmt(available)}`],
      ["Total Dividends Received", `${fmt(data.totalDividendsReceived)}`],
      ["Pending Withdrawal Amount", `${fmt(data.withdrawalPendingAmount)}`],
    ],
    foot: [["Contribution count", String(data.contributionCount)], ["Active loan count", String(data.loanCount)]],
    headStyles: {
      fillColor: [16, 185, 129],
      textColor: 255,
      fontStyle: "bold",
    },
    footStyles: {
      fillColor: [245, 245, 245],
      textColor: [80, 80, 80],
    },
    alternateRowStyles: { fillColor: [250, 250, 250] },
    columnStyles: { 1: { halign: "right" } },
    margin: { left: 15, right: 15 },
  });

  addFooter(doc);

  const safeName = data.memberName.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  doc.save(`member-statement-${safeName}.pdf`);
}

export function exportCooperativeReportPdf(
  data: CoopOverviewData,
  cooperativeName: string
) {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });
  const pageWidth = doc.internal.pageSize.getWidth();
  const today = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  // ── Header ──────────────────────────────────────────────────
  doc.setFontSize(20);
  doc.setTextColor(20, 20, 20);
  doc.text(cooperativeName, pageWidth / 2, 20, { align: "center" });

  doc.setFontSize(14);
  doc.setTextColor(60, 60, 60);
  doc.text("Cooperative Financial Report", pageWidth / 2, 29, {
    align: "center",
  });

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Report Date: ${today}`, pageWidth / 2, 37, { align: "center" });

  doc.setDrawColor(220, 220, 220);
  doc.line(15, 41, pageWidth - 15, 41);

  const fmt = (n: number) => n.toLocaleString();

  // ── Financial Summary Table ──────────────────────────────────
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);
  doc.text("Financial Summary", 15, 50);

  autoTable(doc, {
    startY: 55,
    head: [["Metric", "Value"]],
    body: [
      ["Total Verified Contributions", fmt(data.totalVerifiedContributions)],
      ["Total Outstanding Loan Balance", fmt(data.totalOutstandingLoanBalance)],
      ["Total Dividends Paid", fmt(data.totalDividendsPaid)],
      ["Net Capital (Contributions − Loans)", fmt(data.netCapital)],
    ],
    headStyles: {
      fillColor: [16, 185, 129],
      textColor: 255,
      fontStyle: "bold",
    },
    alternateRowStyles: { fillColor: [250, 250, 250] },
    columnStyles: { 1: { halign: "right" } },
    margin: { left: 15, right: 15 },
  });

  // ── Membership & Loans Table ──────────────────────────────────
  // Get Y position after previous table
  const afterFinancial = (doc as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? 120;

  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);
  doc.text("Membership & Loans", 15, afterFinancial + 10);

  autoTable(doc, {
    startY: afterFinancial + 15,
    head: [["Metric", "Count"]],
    body: [
      ["Total Members", String(data.totalMembers)],
      ["Verified Members", String(data.verifiedMembers)],
      ["Unverified Members", String(data.unverifiedMembers)],
      ["Active Loans", String(data.activeLoanCount)],
      ["Total Loans", String(data.totalLoanCount)],
      ["Defaulted Loans (90+ days)", String(data.defaultedLoanCount)],
      ["Dividend Payouts", String(data.dividendPayoutsCount)],
    ],
    headStyles: {
      fillColor: [59, 130, 246],
      textColor: 255,
      fontStyle: "bold",
    },
    alternateRowStyles: { fillColor: [250, 250, 250] },
    columnStyles: { 1: { halign: "right" } },
    margin: { left: 15, right: 15 },
  });

  addFooter(doc);

  const safeName = cooperativeName.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  doc.save(`cooperative-report-${safeName}.pdf`);
}
